var mongoose = require('mongoose');

var IncidentSchema = new mongoose.Schema({
  raisedby: String,
  casewoker:String,
contactnum:String,
teamleader:String,
location: String,
team: String,
workgroup: String,
g7: String,
achieved: String,
comp_area: String,
sub_area: String,
fun_area_affe: String,
srnum: String,
srsubstat: String,
casenum: String,
mastcasenum: String,
pp_nino: String,
pp_name: String,
rp_nino: String,
rp_name: String,
bicc_rep_name: String,
bicc_ans_subj_area: String,
report_name: String,
report_num: String,
folder_name: String,
report_col_name: String,
col_item_name: String,
SER: Boolean,
SET: Boolean,
case_prog_aff: Boolean,
pay_affect: Boolean,
reputation_risk: Boolean,
case_affected: Boolean,
background_info: String,
procedural_path: String,
error_msg: String,
other_info: String,
  updated_at: { type: Date, default: Date.now },
});

module.exports = mongoose.model('Incident', IncidentSchema);
